### ISSUE TITLE
Sequence Diagram for API

### ISSUE THREAD

**Issue by buseg** [bounswe/bounswe2019group2#111]
## Prerequisite

- [x] I am using the latest version of the code, and checked the documentation related to my needs.

* **I'm submitting a ... **
  - [x] documentation request

* **Briefly describe the nature of the issue. If test request, please provide the functionality. If feature request, please provide related requirement.**

Sequence diagram needs to be added for our API code.

* **Other information** 

Please add your design page link to this page: https://github.com/bounswe/bounswe2019group2/wiki/Design-for-API

* **Deadline for resolution:** 
5 May, 2019 20:00

**Comment by rdilruba** [comment]
done. can you please review ? @ynskardas

**Comment by ynskardas** [comment]
I have reviewed, I have added 1 more png files. and it is done.
