### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by buseg** [bounswe/bounswe2019group2#115]
## Prerequisite

- [x] I am using the latest version of the code, and checked the documentation related to my needs.

* **I'm submitting a ... (remove the irrelevant one)**
  - [x] documentation request

* **Briefly describe the nature of the issue. If test request, please provide the functionality. If feature request, please provide related requirement.**

Create a user manual for the API.

* **Deadline for resolution:** 

May 6, 2019 10:00

**Comment by buseg** [comment]
Manual can be found here: https://github.com/bounswe/bounswe2019group2/wiki/User-Manual

**Comment by fatih-iver** [comment]
I think we should mention the list parity API in the "listing parities section" rather than mentioning the latest table on the main page.
