### ISSUE TITLE
Create Requirements page

### ISSUE THREAD

**Issue by rdilruba** [bounswe/bounswe2019group2#16]
2 types of requirements 
-Functional
-Non-Functional

**Comment by adilnumancelik2017400198** [comment]
User related functional reqs are done. Check it.

**Comment by buseg** [comment]
I guess I am done for now, I will check when other requirements are written.

**Comment by yemreinci** [comment]
@aysurzayeb and I finished writing the non-func reqs.

**Comment by furkangok** [comment]
System requirements are done. Could you please check it and let me know if anything is missing.

**Comment by buseg** [comment]
I think we can close the issue if everyone is happy.
