### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by mertyg** [bounswe/bounswe2019group2#21]
this issue is expected to be used as a discussion page for the group name. not an urgent one though.

let me start off: TrAiders 😃

**Comment by ynskardas** [comment]
"TrAiders" seems like illegal bet site name. However, i like so much.

**Comment by adilnumancelik2017400198** [comment]
i am ok with TrAiders.

**Comment by mcanbayraktar** [comment]
TrAiders is OK for me too. How about deciding group name in today's meeting? Maybe we find a better alternative while discussing as group. See you on meeting guyzz

**Comment by mertyg** [comment]
👍🏻 It’s already in the meeting agenda 🤓

**Comment by mcanbayraktar** [comment]
> 👍🏻 It’s already in the meeting agenda 🤓

Awww my bad, thanks :)

**Comment by fatih-iver** [comment]
I'm happy with TrAiders.
