### ISSUE TITLE
Update requirements page according to feedback

### ISSUE THREAD

**Issue by yemreinci** [bounswe/bounswe2019group2#23]
Here are the things we need to do:

Glossary
- [x] Article:Normally, the definition is correct. However, for traders platform, it is incorrect. Article is a piece of writing of users of traders platform.
- [x] Basic user: Give some example to basic application functionalities.
- [x] Follow: Where is the subject of the sentence?
- [x] Guest: Application functionalities like what? How does it differ from basic user rather than signing in?
 
User requirements
 - [x] Divide functional requirements into two parts. First one should be user requirements, and the other should be system requirements (i.e., system requirements should be under functional requirements).
- [x] You should distinguish trading user from basic user for signing up. For instance, trading user should provide more information (e.g., IBAN number) to sign up compared to basic user.
- [x] 1.1.1.1. what is appropriate password?
- [x] 1.3.2 and 1.3.3. have so many requirements in common. Try to combine them instead of rewriting.
- [x] 1.4.1. give at least three example for each trading equipment.
 
System requirements
- [x] 3.2.1. The system shall also provide portfolio to the users based on their histories.
- [x] 3.2.2. It is incorrect. The users shall provide predictions, not the system.
- [x] 3.3.1. How about aconomic events?
- [x] 3.3.3. Give more detail.
 
Non-functional requirements
- [x] 2.3.5. minimum failure?
- [x] 2.4. how about W3C Web Annotation Protocol?

**Comment by adilnumancelik2017400198** [comment]
We need to do another update according to 2nd customer meeting. I am going to classify new requirements soon.

**Comment by adilnumancelik2017400198** [comment]
Customer Meeting #2 

- [ ] 3.2  System req.

- [ ] 3.3 user req.

- [ ] 3.4 user req.

- [ ] 3.5 user req.

- [ ] 3.6 system req.

- [ ] 3.7 i cant not understand

- [ ] 3.8 system req.

- [ ] 3.9 user req.

- [ ] 3.10 system req.

**Comment by fatih-iver** [comment]
There was a grammatical mistake in 3.7. I have fixed it. You may check it again.

**Comment by rdilruba** [comment]
> Customer Meeting #2
> 
>     * [ ]  3.2  System req.
> 
>     * [x]  3.3 user req.
> 
>     * [x]  3.4 user req.
> 
>     * [x]  3.5 user req.
> 
>     * [x]  3.6 system req.
> 
>     * [x]  3.7 user req.
> 
>     * [ ]  3.8 system req.
> 
>     * [x]  3.9 user req.
> 
>     * [ ]  3.10 system req.

I updated some of the requirements, but I am not sure about the others.

**Comment by adilnumancelik2017400198** [comment]
3.2 fits 1.4 Trading Equipments under user requirements. But the whole 1.4 Trading Equipments section fits system requirements better i think. I don't know what to say about 3.8 and 3.10.

**Comment by yemreinci** [comment]
Reqs related to admins are added. also added a non-func req for support of turkish characters. see req 2.3.7.
closing this.
