### ISSUE TITLE
Predictions Tests

### ISSUE THREAD

**Issue by mertyg** [bounswe/bounswe2019group2#254]
## Prerequisite

- [X] I am using the latest version of the code, and checked the documentation related to my needs.

* **I'm submitting a ... (remove the irrelevant one)**
  - [X] test request

* **Briefly describe the nature of the issue. If test request, please provide the functionality. If feature request, please provide related requirement.**
Predictions API tests are needed.

**Comment by yemreinci** [comment]
https://github.com/bounswe/bounswe2019group2/blob/master/traiders/backend/api/test/test_prediction.py
