### ISSUE TITLE
review communication plan

### ISSUE THREAD

**Issue by mertyg** [bounswe/bounswe2019group2#26]

**Comment by mcanbayraktar** [comment]
I reviewed the comm plan.  Can you plase check it?
Btw while I was stalking some old plans, I realised that we would need a cloud platform to store/view important files.  How about adding Google Drive into our communication plan?

**Comment by buseg** [comment]
The new plan looks nice

**Comment by mertyg** [comment]
I think the Drive makes sense, and the plan looks good :+1:

**Comment by mcanbayraktar** [comment]
Well thanks for your appreciation. I'm gonna handle Drive stuff asap 👍
