### ISSUE TITLE
Unify the dates in the DB

### ISSUE THREAD

**Issue by mertyg** [bounswe/bounswe2019group2#267]
## Prerequisite

- [X] I am using the latest version of the code, and checked the documentation related to my needs.

* **I'm submitting a ... (remove the irrelevant one)**
  - [X] bug report

* **Briefly describe the nature of the issue. If test request, please provide the functionality. If feature request, please provide related requirement.**
There are several different formats for date used in the DB. (reported by @fatih-iver )
For example: created_at ve date_joined fields have different date formats. We need to unify those.

**Comment by yemreinci** [comment]
Turned out they all have ISO-8601 format. Closing this.
