### ISSUE TITLE
scenario visual design

### ISSUE THREAD

**Issue by mertyg** [bounswe/bounswe2019group2#27]

**Comment by buseg** [comment]
You can find the design here: 
https://www.figma.com/file/O1NdhwPPn6OpwX8h7LdKs2Gy/CMPE352-G2
We can continue on this platform.

**Comment by furkangok** [comment]
Done.

**Comment by mcanbayraktar** [comment]
I think this issue was completed a few days ago. What do you think @furkangok ? If you agree with me, you can close the issue bro.
