### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by mcanbayraktar** [bounswe/bounswe2019group2#35]
Deadline: Wednesday 17:00

**Comment by yemreinci** [comment]
Please review the class diagram [here](https://www.dropbox.com/s/tjiebtjluwq8guz/CMPE352%20Traders%20Platform%20Class%20Diagram%20%282%29.pdf?dl=0).

**Comment by mertyg** [comment]
looks perfect 💯

**Comment by yemreinci** [comment]
I did a few last revisions and uploaded. I will keep the issue open until sequence diagrams are completed as they may need other functions i forgot.

**Comment by yemreinci** [comment]
Just updated the class diagram. Methods now have parameters and should be fully consistent with seq diagrams. @mertyg if you see anything wrong, let me know.
