### ISSUE TITLE
Updating Use Case Diagrams

### ISSUE THREAD

**Issue by aysurzayeb** [bounswe/bounswe2019group2#45]

**Comment by aysurzayeb** [comment]
i will close the issue for now, there is a little adjustments left i will edit the .uxf and upload it to repo ASAP

**Comment by buseg** [comment]
Current diagram: https://www.lucidchart.com/invitations/accept/25a2fba7-e1c5-466c-baf7-1f17da0fb559

**Comment by mcanbayraktar** [comment]
I edited a few minor things from the link above. Thanks for your effort guyzz 👍

**Comment by mertyg** [comment]
@buseg @mcanbayraktar @aysurzayeb i think we can close this issue now
