### ISSUE TITLE
Review Use Case Diagram

### ISSUE THREAD

**Issue by buseg** [bounswe/bounswe2019group2#49]
Can you please check if anything is missing or seems odd?

**Comment by mertyg** [comment]
I think the diagram is mostly okay, good job guys! 

A few observations:

1. We have seperate related use cases about articles in different places. Wouldn't it be better if we combine them together?
2. We don't have an exact "Sign-In" use case, but I assume you considered it as a branch of registration part. Wouldn't it be better if we include Sign In use cases, for the sake of completeness?
3. We don't have anything related to "Manual Investments"(i'm not sure if we should include that, but just wanted to share the observation)
4. I'm not sure if we should do this, but just an idea: We have 1 general search use case, but the extensions may differ for different types of purposes. For example, we can search an article by author, or we can search a portfolio by a specific trading equipment, or we can search a user by name, etc. It might be easier to elaborate on this if we split the search use cases by the element we are searching for. Again, just an idea.

**Comment by mcanbayraktar** [comment]
Use Case Diagram looks very good :) I think there should be a bubble named like "Withdraw Money from Account" besides "Transfer Money to the System". 
Congrats for your effort 👍👍

**Comment by buseg** [comment]
1. Agreed, we should add view articles under main.
2. Sign In will be added.
3. Under Basic, view profit/loss there is a choice for manual entry. This is what I understood from customer meetings and feedback but I might be wrong.
4. We discussed this in the last meeting but we couldn't come to an agreement. MAybe we should talk aboout this in our next meeting.

**Comment by buseg** [comment]
@mertyg Thank you very much for the feedback 😄

**Comment by mcanbayraktar** [comment]
Updated the diagram based on your feedback @mertyg. Thanks 👍
