### ISSUE TITLE
Agenda of Meeting #7

### ISSUE THREAD

**Issue by mcanbayraktar** [bounswe/bounswe2019group2#51]
I prepared the agenda of meeting 7 and added a topic that I think we should talk about it.

**Comment by uskudarli** [comment]
Note: It will be useful if you give link to meeting agenda you created, it will make it very easy to click and see. 

Also, a date for the meeting #7 will be nice for reference.

Finally assignees will alert people who should pay attention. Here it is everyone, but then it is clear that that is the attention.

Nice Labeling.

**Comment by mcanbayraktar** [comment]
It makes sense, a link could be useful 👍 
I created the next meeting's page as agenda and added topics into it. Anyone can reach the agenda from [here](https://github.com/bounswe/bounswe2019group2/wiki/Meeting-%237) . 
Thanks for the comment. 
See you tomorrow 😄
