### ISSUE TITLE
Upload Meeting Notes #7

### ISSUE THREAD

**Issue by ozgursolak** [bounswe/bounswe2019group2#53]

**Comment by ozgursolak** [comment]
I uploaded the meeting note #7 : https://github.com/bounswe/bounswe2019group2/wiki/Meeting-%237

**Comment by mertyg** [comment]
I think there were missing and wrong things in the meeting note. I have just updated them, please review

**Comment by ozgursolak** [comment]
thanks for your updates Mert.

**Comment by ozgursolak** [comment]
I closed the final situation of our notes #7 : https://github.com/bounswe/bounswe2019group2/wiki/Meeting-%237
