### ISSUE TITLE
Writing Executive Summary

### ISSUE THREAD

**Issue by buseg** [bounswe/bounswe2019group2#54]
Summary of project status and any changes that are
planned for moving forward.

**Comment by buseg** [comment]
@mcanbayraktar  can you check the Executive Summary? https://docs.google.com/document/d/1UhQbRPKQp3rqwikSVuXJTYv-X7C2y3j07FbZfj2uPuc/edit

**Comment by mcanbayraktar** [comment]
It seems OK. Great job 👍
