### ISSUE TITLE
Preparing Project Plan

### ISSUE THREAD

**Issue by furkangok** [bounswe/bounswe2019group2#59]

**Comment by adilnumancelik2017400198** [comment]
Ben ilk iki haftalık kısmı alıyorum, çakışma olmasın. En son planın gelecek kısmını beraber yapıp, temize çekebiliriz.

**Comment by adilnumancelik2017400198** [comment]
[project plan draft.xlsx](https://github.com/bounswe/bounswe2019group2/files/3050404/project.plan.draft.xlsx)

**Comment by fatih-iver** [comment]
[Here](https://drive.google.com/open?id=1vnkOg78qKZfOhgZXGKJbeEoNqOUX8g0Z) are the project plan file and its pdf version.
