### ISSUE TITLE
Decide on the issue labels

### ISSUE THREAD

**Issue by yemreinci** [bounswe/bounswe2019group2#6]
We should decide on the issue labels we will use throughout the project. This is an open discussion, so please write your suggestions as a comment, and also give thumbs up (or down) for others'.

**Comment by yemreinci** [comment]
If we are going to have discussions as this one, we can label them by **"Discussion"**

**Comment by adilnumancelik2017400198** [comment]
> If we are going to have discussions as this one, we can label them by **"Discussion"** 

+1

we can add **"Assignment Needed"**, **"Everyone"**

**Comment by buseg** [comment]
High Priority label seems useful as well.

**Comment by mertyg** [comment]
A blogpost with a neat approach:

> https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
> I think the scheme that this blogpost suggests is pretty neat. The idea of same group of categories would make it really easy to follow the issues for anybody, saving time.

Considering the "everyone" and "assignment needed" suggestions above, I'd suggest adding a 4th group of labels: "People"; i.e. "People: Everyone" "People: Assignment Needed" "People: Assigned" for this project.
