### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by mertyg** [bounswe/bounswe2019group2#67]
Deadline: Friday, April 26

**Comment by mertyg** [comment]
Can be found [here](https://github.com/bounswe/bounswe2019group2/wiki/API-System-Requirements)

**Comment by mertyg** [comment]
@buseg can you please review the [requirements](https://github.com/bounswe/bounswe2019group2/wiki/API-System-Requirements)?

**Comment by buseg** [comment]
Just finished reviewing, great work! Seems to include every requirement about manual investment. We can update it later if needed.
