### ISSUE TITLE
Document communication plan

### ISSUE THREAD

**Issue by yemreinci** [bounswe/bounswe2019group2#7]
Create a wiki page for our communication plan. It should include the communication channels we'll use, and a table that describes our meetings. For inspiration: [https://github.com/bounswe/bounswe2018group9/wiki/Communication-Plan](url)

**Comment by adilnumancelik2017400198** [comment]
Slack kullanalım mı? Ayrıca şu an için tamam, düzeltme veya ekleme yapılması gerektiğini düşünen varsa bildirebilir.

**Comment by uskudarli** [comment]
> Should we use slack?

Sounds good. And customize it with fantastic integrations supporting software teams...
