### ISSUE TITLE
Deploy app to AWS EC2

### ISSUE THREAD

**Issue by yemreinci** [bounswe/bounswe2019group2#73]
We are required to deploy this app on a AWS EC2 instance. Things to do:
- [x]  Register AWS
- [x] Create an EC2 instance with Ubuntu installed (cheapest one should be enough for our needs).
- [ ] Collect SSH keys from team members and add them to the machine.
- [ ] Run the app.
- [ ] Enable https (get an ssl certificate from https://letsencrypt.org)
- [ ] Register a domain name for our project. (www.freenom.com offers free domain names)

**Comment by yemreinci** [comment]
We launched an EC2 instance. You can send your ssh public key to @buseg if you need access to the machine.

**Comment by fatih-iver** [comment]
Here is my public key @buseg :

[public key.zip](https://github.com/bounswe/bounswe2019group2/files/3124733/public.key.zip)
