### ISSUE TITLE
Edit Wiki Sidebar

### ISSUE THREAD

**Issue by mcanbayraktar** [bounswe/bounswe2019group2#9]
To get a more organized and indexed sidebar

**Comment by yemreinci** [comment]
Cool!
I converted the absolute links you used for members to relative links. I guess you copy pasted each link one by one, that would work but using relative links to the wiki pages is way more easy. check [this](https://help.github.com/articles/editing-wiki-content/#adding-links). Also the links to pages that aren't created yet are colored red, and it automatically forwards you to page creation when you click on them.
