### ISSUE TITLE
Tests for Total Profit/Loss Calculation

### ISSUE THREAD

**Issue by mertyg** [bounswe/bounswe2019group2#93]
## Prerequisite

- [X] I am using the latest version of the code, and checked the documentation related to my needs.

* **I'm submitting a ... (remove the irrelevant one)**
  - [X] test request

* **Briefly describe the nature of the issue. If test request, please provide the functionality. If feature request, please provide related requirement.**

Tests for total profit calculation are needed.

* **Deadline for resolution:** 
May 6, 2019

**Comment by buseg** [comment]
Code added here #113

**Comment by mertyg** [comment]
@buseg i think we are done here
