### ISSUE TITLE
1.3.2,1.3.3, 1.3.4 Tests for Investments API

### ISSUE THREAD

**Issue by mertyg** [bounswe/bounswe2019group2#99]
## Prerequisite

- [X] I am using the latest version of the code, and checked the documentation related to my needs.

* **I'm submitting a ... (remove the irrelevant one)**
  - [X] test request

* **Briefly describe the nature of the issue. If test request, please provide the functionality. If feature request, please provide related requirement.**

Tests for loss/profit calculation are needed. 

* **Deadline for resolution:** 
May 6, 2019

**Comment by fatih-iver** [comment]
I will write the tests for the requirement 1.3.2.

**Comment by mertyg** [comment]
I have written the test for 1.3.4

**Comment by fatih-iver** [comment]
PR #118  is ready to review for the test case 1.3.2.
